export class CustomersFDb
{

    public static data = [
        {
            'id': '1',
            'code': '70d4d7d0',
            'name': 'Customer Title 01',
            'description': 'Customer Description 01',
            'active': true,
            'recordOnly': false,
            'detDescription': 'Customer Detailed Description 01',
            'address:': 'Address 01',
            'postalCode': '39.97',
            'country': 'Germany',
            'contactPerson': 'Person 01',
            'phone': '0744848477',
            'email': 'person01@email.com',
            'taxNumber':'01',
            'otherInfo': 'otherInfo 01',
            'item': 'Item 01',
            'price': '24.25',
            'currency': 'EUR',
            'discount': '0',
            'createdOn': '2018/04/25 02:07:59',
            'updatedOn': '2018/05/27 02:07:59',
        },
        {
            'id': '2',
            'code': '87054d7d0',
            'name': 'Customer Title 02',
            'description': 'Customer Description 02',
            'active': false,
            'recordOnly': true,
            'detDescription': 'Customer Detailed Description 02',
            'address:': 'Address 02',
            'postalCode': '747475',
            'country': 'Great Britain',
            'contactPerson': 'Person 02',
            'phone': '0752145744',
            'email': 'person02@email.com',
            'taxNumber':'02',
            'otherInfo': 'otherInfo 02',
            'item': 'Item 02',
            'price': '32.25',
            'currency': 'USD',
            'discount': '0',
            'createdOn': '2016/04/25 04:07:59',
            'updatedOn': '2018/05/27 02:07:59',
        },
        {
            'id': '3',
            'code': '8704524',
            'name': 'Customer Title 03',
            'description': 'Customer Description 03',
            'active': true,
            'recordOnly': false,
            'detDescription': 'Customer Detailed Description 03',
            'address:': 'Address 03',
            'postalCode': '747375',
            'country': 'Great Britain',
            'contactPerson': 'Person 03',
            'phone': '0752145744',
            'email': 'person03@email.com',
            'taxNumber':'02',
            'otherInfo': 'otherInfo 03',
            'item': 'Item 03',
            'price': '3.25',
            'currency': 'USD',
            'discount': '0',
            'createdOn': '2016/03/2 04:07:59',
            'updatedOn': '2017/05/27 02:07:59',
        },
        {
            'id': '4',
            'code': '44144',
            'name': 'Customer Title 04',
            'description': 'Customer Description 04',
            'active': true,
            'recordOnly': false,
            'detDescription': 'Customer Detailed Description 04',
            'address:': 'Address 04',
            'postalCode': '2145454',
            'country': 'France',
            'contactPerson': 'Person 04',
            'phone': '0774544444',
            'email': 'person04@email.com',
            'taxNumber':'0',
            'otherInfo': 'otherInfo 04',
            'item': 'Item 04',
            'price': '225',
            'currency': 'EUR',
            'discount': '0',
            'createdOn': '2016/03/2 04:07:59',
            'updatedOn': '2017/05/27 02:07:59',
        },
        {
            'id': '5',
            'code': '11124244',
            'name': 'Customer Title 05',
            'description': 'Customer Description 05',
            'active': false,
            'recordOnly': true,
            'detDescription': 'Customer Detailed Description 05',
            'address:': 'Address 05',
            'postalCode': '01221212',
            'country': 'Romania',
            'contactPerson': 'Person 05',
            'phone': '0233122111',
            'email': 'person054@email.com',
            'taxNumber':'0',
            'otherInfo': 'otherInfo 05',
            'item': 'Item 05',
            'price': '2.22',
            'currency': 'GBP',
            'discount': '1',
            'createdOn': '2016/03/2 04:07:59',
            'updatedOn': '2017/05/27 02:07:59',
        }
    ]
}
