export class ItemsFDb
{

    public static items = [
        {
            'id': '1',
            'category': 'c1',
            'name': 'category1',
            'type': '100',
            'minumumStoc': '0',
            'warranty': '2023/02/2',
            'specialDiscount': '0',
            'maximumDiscount': '0',
            'primaryUm': 'Kg',
            'netWeight': '0',
            'grossWeight': '0',
            'width': '0',
            'height': '0',
            'depth': '0',
            'um': 'M',
            'supDiscount': '0',
            'transport': '0',
            'customs': '0',
            'directCosts': '0',
            'salePrice': '0',
            'currency': 'M',
            'description': 'A nice description',
            'image': '0',
            'createdOn': '2019/02/25',
            'updatedOn': '2019/03/3',

        },
        {
            'id': '2',
            'category': 'c2',
            'name': 'category2',
            'type': '200',
            'minumumStoc': '0',
            'warranty': '2022/04/25',
            'specialDiscount': '0',
            'maximumDiscount': '0',
            'primaryUm': 'KOS',
            'netWeight': '0',
            'grossWeight': '0',
            'width': '0',
            'height': '0',
            'depth': '0',
            'um': 'M',
            'supDiscount': '0',
            'transport': '0',
            'customs': '0',
            'directCosts': '0',
            'salePrice': '0',
            'currency': 'M',
            'description': 'Another nice description',
            'image': '0',
            'createdOn': '2018/04/25',
            'updatedOn': '2018/04/25',

        },
        {
            'id': '3',
            'category': 'c3',
            'name': 'category3',
            'type': '200',
            'minumumStoc': '0',
            'warranty': '2022/04/25',
            'specialDiscount': '0',
            'maximumDiscount': '0',
            'primaryUm': 'KOS',
            'netWeight': '0',
            'grossWeight': '0',
            'width': '0',
            'height': '0',
            'depth': '0',
            'um': 'M',
            'supDiscount': '0',
            'transport': '0',
            'customs': '0',
            'directCosts': '0',
            'salePrice': '0',
            'currency': 'M',
            'description': 'Another nice description',
            'image': '0',
            'createdOn': '2018/04/25',
            'updatedOn': '2018/04/25',

        }

       
    ]
}
